version: "2"
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocyclo
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - protogetter
    - reassign
    - recvcheck
    - revive
    - spancheck
    - testifylint
    - unparam
    - zerologlint
  disable:
    - asciicheck
    - exhaustive
    - gosec
    - noctx
    - rowserrcheck
    - sqlclosecheck
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
