name: Reviewdog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@dd3fda91790ca90e75049e5c767509dc0ec7d99b # v2
        with:
          github_token: ${{ github.token }}
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          reporter: github-pr-review
